#!/usr/bin/env python3
"""Install, inspect, and bootstrap the Agentic Engineering toolbelt.

This is the provider-neutral entry point. It uses only the Python standard library and
keeps every write idempotent and attributable to this toolbelt.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import io
import json
import os
import pathlib
import platform
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
from collections.abc import Iterable


REPO = pathlib.Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO / "toolbelt.json"
MANAGED_MARKER = ".agentic-engineering-managed.json"
INSTALL_STATE_RELATIVE = pathlib.Path(".agentic-engineering") / "install-state.json"
GENERATED_HEADER = "# Generated by Agentic Engineering. Do not edit by hand."
PROVIDERS = ("claude", "codex", "pi", "hermes")
# Hermes ships its own bundled skills under these names (plan, tdd, dogfood) or
# owns the namespace as a category directory (research); installing the toolbelt's
# would shadow or collide. The agentic-engineering router skill covers them from
# the repo.
HERMES_EXCLUDED = frozenset({"plan", "tdd", "dogfood", "research"})
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
# Official SemVer 2.0.0 shape (semver.org), mirroring the release publisher:
# ASCII + fullmatch, because `$` accepts a trailing newline and a bare `\d`
# accepts non-ASCII digits.
SEMVER_RE = re.compile(
    r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?"
    r"(?:\+[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*)?",
    re.ASCII,
)
MAX_SCAFFOLD_BYTES = 1024 * 1024


class ToolbeltError(RuntimeError):
    """An expected, user-actionable toolbelt failure."""


def load_manifest() -> dict[str, object]:
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ToolbeltError(f"cannot read {MANIFEST_PATH}: {exc}") from exc


def sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _decode_scalar(value: str) -> str:
    """Decode a frontmatter scalar to its real string value. Double-quoted
    values are JSON strings, so escapes (``\\"``, ``\\uXXXX``) are resolved
    rather than passed through verbatim — otherwise re-encoding them for a
    provider adapter double-escapes the quotes and turns em-dashes into
    ``\\u2014``. Other quoted values just have their surrounding quotes stripped."""
    if value[:1] == '"':
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            pass
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_frontmatter(path: pathlib.Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ToolbeltError(f"{path}: missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ToolbeltError(f"{path}: unterminated YAML frontmatter")
    fields: dict[str, str] = {}
    for line in text[4:end].splitlines():
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if match:
            fields[match.group(1)] = _decode_scalar(match.group(2).strip())
    return fields, text[end + 5 :]


def skill_dirs() -> list[pathlib.Path]:
    root = REPO / "skills"
    if not root.is_dir():
        raise ToolbeltError(f"canonical skills directory is missing: {root}")
    return sorted(path for path in root.iterdir() if path.is_dir() and (path / "SKILL.md").is_file())


def hermes_skill_dirs() -> list[pathlib.Path]:
    """Skills installed into Hermes: all canonical skills minus HERMES_EXCLUDED."""
    return [source for source in skill_dirs() if source.name not in HERMES_EXCLUDED]


def hermes_skills_root(home: pathlib.Path) -> pathlib.Path:
    """Hermes skills root: $HERMES_HOME/skills when set, else ~/.hermes/skills.

    Always absolute: a relative HERMES_HOME would change meaning with the process
    CWD and corrupt artifact records (relative records vs absolute validation).
    """
    env = os.environ.get("HERMES_HOME")
    if env:
        return pathlib.Path(os.path.abspath(os.path.expanduser(env))) / "skills"
    return pathlib.Path(os.path.abspath(home.expanduser())) / ".hermes" / "skills"


def render_codex_agent(source: pathlib.Path) -> str:
    fields, body = parse_frontmatter(source)
    for required in ("name", "description"):
        if not fields.get(required):
            raise ToolbeltError(f"{source}: missing {required!r}")
    if "'''" in body:
        raise ToolbeltError(f"{source}: prompt contains unsupported TOML literal delimiter")
    return (
        f"{GENERATED_HEADER}\n"
        f"name = {json.dumps(fields['name'], ensure_ascii=False)}\n"
        f"description = {json.dumps(fields['description'], ensure_ascii=False)}\n"
        "developer_instructions = '''\n"
        f"{body.rstrip()}\n"
        "'''\n"
    )


def generated_codex_agents() -> dict[pathlib.Path, str]:
    output: dict[pathlib.Path, str] = {}
    for source in sorted((REPO / "agents").glob("*.md")):
        fields, _ = parse_frontmatter(source)
        name = fields.get("name")
        if not name:
            raise ToolbeltError(f"{source}: missing agent name")
        if not NAME_RE.fullmatch(name):
            raise ToolbeltError(f"{source}: unsafe agent name {name!r}")
        output[REPO / "providers" / "codex" / "agents" / f"{name}.toml"] = render_codex_agent(source)
    return output


def render_claude_skill(source: pathlib.Path) -> str:
    fields, body = parse_frontmatter(source)
    name = fields.get("name", "")
    description = fields.get("description", "")
    if not name or not description:
        raise ToolbeltError(f"{source}: missing name or description")
    policy = load_manifest().get("skillPolicy", {})
    explicit = set(policy.get("explicit", [])) if isinstance(policy, dict) else set()
    arguments = policy.get("arguments", {}) if isinstance(policy, dict) else {}
    lines = ["---", f"name: {name}", f"description: {json.dumps(description, ensure_ascii=False)}"]
    if name in explicit:
        lines.append("disable-model-invocation: true")
    if isinstance(arguments, dict) and isinstance(arguments.get(name), str):
        lines.append(f"argument-hint: {json.dumps(arguments[name], ensure_ascii=False)}")
    lines.extend(["---", "", body.rstrip(), ""])
    return "\n".join(lines)


def generated_claude_skills() -> dict[pathlib.Path, bytes]:
    output: dict[pathlib.Path, bytes] = {}
    destination_root = REPO / "providers" / "claude" / "skills"
    for directory in skill_dirs():
        for source in sorted(path for path in directory.rglob("*") if path.is_file()):
            relative = source.relative_to(directory)
            destination = destination_root / directory.name / relative
            if relative == pathlib.Path("SKILL.md"):
                output[destination] = render_claude_skill(source).encode("utf-8")
            else:
                output[destination] = source.read_bytes()
    return output


def generated_provider_files() -> dict[pathlib.Path, bytes]:
    output = generated_claude_skills()
    output.update(
        {path: content.encode("utf-8") for path, content in generated_codex_agents().items()}
    )
    return output


def validate_source(*, check_generated: bool = True) -> list[str]:
    errors: list[str] = []
    # A malformed or non-object primary manifest is a repository finding (gate
    # exit 1), never a broken-tool crash: parse it defensively before use.
    try:
        manifest: object = load_manifest()
    except ToolbeltError as exc:
        errors.append(str(exc))
        manifest = {}
    if not isinstance(manifest, dict):
        errors.append(f"{MANIFEST_PATH}: manifest root must be a JSON object")
        manifest = {}
    names: set[str] = set()
    allowed_frontmatter = {"name", "description"}
    for directory in skill_dirs():
        fields, _ = parse_frontmatter(directory / "SKILL.md")
        name = fields.get("name", "")
        names.add(name)
        if name != directory.name:
            errors.append(f"{directory}: skill name {name!r} does not match directory")
        if not fields.get("description"):
            errors.append(f"{directory}: missing description")
        extras = sorted(set(fields) - allowed_frontmatter)
        if extras:
            errors.append(f"{directory}: provider-specific frontmatter: {', '.join(extras)}")
        if not (directory / "tests.md").is_file():
            errors.append(f"{directory}: missing tests.md")

    workflow = manifest.get("workflow", [])
    if isinstance(workflow, list):
        for phase in workflow:
            if not isinstance(phase, dict):
                errors.append("toolbelt.json: workflow phase must be an object")
                continue
            for name in phase.get("skills", []):
                if name not in names:
                    errors.append(f"toolbelt.json: workflow references unknown skill {name!r}")

    if check_generated:
        expected_files = generated_provider_files()
        for path, expected in expected_files.items():
            actual = path.read_bytes() if path.is_file() else None
            if actual != expected:
                errors.append(f"{path}: generated provider adapter is missing or stale")
        for root in (REPO / "providers" / "claude" / "skills", REPO / "providers" / "codex" / "agents"):
            if root.is_dir():
                extras = sorted(path for path in root.rglob("*") if path.is_file() and path not in expected_files)
                for path in extras:
                    errors.append(f"{path}: stale generated provider file")

    manifest_versions: dict[str, object] = {}
    for rel in ("toolbelt.json", "package.json", ".claude-plugin/plugin.json", ".codex-plugin/plugin.json"):
        path = REPO / rel
        if not path.is_file():
            errors.append(f"{rel}: release manifest is missing")
            continue
        try:
            manifest = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            errors.append(f"{rel}: invalid JSON")
            continue
        if not isinstance(manifest, dict):
            errors.append(f"{rel}: manifest root must be a JSON object")
            continue
        version = manifest.get("version")
        # Every manifest must carry the release identity; a missing version must
        # fail rather than being filtered out of the comparison.
        if not isinstance(version, str) or not version.strip():
            errors.append(f"{rel}: missing or empty `version`")
            continue
        manifest_versions[rel] = version
    if len(set(manifest_versions.values())) > 1:
        errors.append(f"manifest version mismatch: {manifest_versions}")
    elif manifest_versions:
        # The changelog is public consumers' only cross-release diff
        # (docs/publishing.md), so a synchronized version without an entry must
        # not be publishable.
        release = next(iter(manifest_versions.values()))
        if not SEMVER_RE.fullmatch(release):
            # Same contract the publisher enforces at preflight: pre-commit must
            # refuse what publishing would refuse, not advertise "valid" for it.
            errors.append(f"synchronized version {release!r} is not valid SemVer")
        changelog = REPO / "CHANGELOG.md"
        if not changelog.is_file():
            errors.append("CHANGELOG.md is missing")
        elif not changelog_has_release_heading(changelog.read_text(encoding="utf-8"), release):
            errors.append(f"CHANGELOG.md has no heading for version {release}")
    return errors


def changelog_has_release_heading(text: str, release: str) -> bool:
    """A line-anchored `## [<release>]` heading in the *rendered* changelog.

    A matching line inside a fenced code block is a documented example, not the
    release entry — the same distinction the plan lint draws — so fenced content
    is excluded before matching. Mirrored by the release publisher's preflight.
    """
    heading = re.compile(rf"^## \[{re.escape(release)}\]")
    fence: tuple[str, int] | None = None
    for line in text.splitlines():
        match = re.match(r" {0,3}(`{3,}|~{3,})", line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = (marker[0], len(marker))
            elif marker[0] == fence[0] and len(marker) >= fence[1] and line.strip() == marker:
                fence = None
            continue
        if fence is None and heading.match(line):
            return True
    return False


def generate(*, check: bool) -> int:
    expected = generated_provider_files()
    generated_roots = (
        REPO / "providers" / "claude" / "skills",
        REPO / "providers" / "codex" / "agents",
    )
    actual = {
        path
        for root in generated_roots
        if root.is_dir()
        for path in root.rglob("*")
        if path.is_file()
    }
    stale = [path for path, content in expected.items() if not path.is_file() or path.read_bytes() != content]
    stale.extend(sorted(actual - set(expected)))
    if stale and not check:
        for root in generated_roots:
            if root.exists():
                shutil.rmtree(root)
        for path, content in expected.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
            print(f"generated {path.relative_to(REPO)}")
    if check and stale:
        for path in sorted(set(stale)):
            print(f"stale generated file: {path.relative_to(REPO)}")
        return 1
    if not stale:
        print("provider adapters: current")
    return 0


def marker_payload(source: pathlib.Path) -> dict[str, object]:
    manifest = load_manifest()
    return {
        "name": manifest["name"],
        "schemaVersion": 2,
        "source": str(source),
        "version": manifest["version"],
    }


def managed_dir_snapshot(path: pathlib.Path) -> dict[str, str]:
    return {
        candidate.relative_to(path).as_posix(): sha256(candidate)
        for candidate in sorted(path.rglob("*"))
        if candidate.is_file() and candidate.name != MANAGED_MARKER
    }


def managed_dir_marker(path: pathlib.Path) -> dict[str, object] | None:
    marker = path / MANAGED_MARKER
    if not marker.is_file():
        return None
    try:
        data = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if data.get("name") == "agentic-engineering" else None


def is_managed_dir(path: pathlib.Path) -> bool:
    return managed_dir_marker(path) is not None


def require_pristine_managed_dir(path: pathlib.Path) -> None:
    marker = managed_dir_marker(path)
    if marker is None:
        raise ToolbeltError(f"refusing to replace unmanaged directory: {path}")
    expected = marker.get("files")
    if not isinstance(expected, dict):
        raise ToolbeltError(
            f"managed directory has no content inventory: {path}; rerun with --force once"
        )
    actual = managed_dir_snapshot(path)
    if actual != expected:
        raise ToolbeltError(f"managed directory was edited since installation: {path}")


def copy_managed_dir(
    source: pathlib.Path,
    destination: pathlib.Path,
    *,
    force: bool,
    dry_run: bool,
    extra_files: dict[str, str] | None = None,
) -> None:
    """Copy a managed directory, optionally injecting extra files.

    ``extra_files`` maps a relative path to content; the files are written into the
    candidate before the managed marker is snapshotted, so the inventory and the
    directory always agree (re-install pristine checks stay green).
    """
    destination_exists = destination.exists() or destination.is_symlink()
    if destination_exists and not force:
        require_pristine_managed_dir(destination)
    action = "update" if destination_exists else "install"
    print(f"{action}: {destination}")
    if dry_run:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    temp_root = pathlib.Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.agentic-", dir=destination.parent)
    )
    candidate = temp_root / "candidate"
    backup = temp_root / "previous"
    moved_previous = False
    try:
        shutil.copytree(source, candidate)
        if extra_files:
            for relative, content in extra_files.items():
                target = candidate / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
        marker = {**marker_payload(source), "files": managed_dir_snapshot(candidate)}
        (candidate / MANAGED_MARKER).write_text(
            json.dumps(marker, indent=2) + "\n", encoding="utf-8"
        )
        if destination_exists:
            os.replace(destination, backup)
            moved_previous = True
        try:
            os.replace(candidate, destination)
        except BaseException:
            if moved_previous and not destination.exists():
                os.replace(backup, destination)
            raise
        if moved_previous:
            if backup.is_dir() and not backup.is_symlink():
                shutil.rmtree(backup)
            else:
                backup.unlink(missing_ok=True)
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)


def managed_sidecar(path: pathlib.Path) -> pathlib.Path:
    return path.with_name(f".{path.name}.agentic-engineering.json")


def write_managed_file(
    path: pathlib.Path,
    content: str,
    *,
    force: bool,
    dry_run: bool,
    executable: bool = False,
) -> None:
    sidecar = managed_sidecar(path)
    if path.exists() and not force:
        if not sidecar.is_file():
            raise ToolbeltError(f"refusing to replace unmanaged file: {path}")
        try:
            prior = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ToolbeltError(f"invalid managed-file marker: {sidecar}") from exc
        if prior.get("sha256") != sha256(path):
            raise ToolbeltError(f"managed file was edited since installation: {path}")
    action = "update" if path.exists() else "install"
    print(f"{action}: {path}")
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable and os.name != "nt":
        path.chmod(path.stat().st_mode | 0o755)
    sidecar.write_text(
        json.dumps({**marker_payload(REPO), "sha256": sha256(path)}, indent=2) + "\n",
        encoding="utf-8",
    )


def launcher_path(home: pathlib.Path) -> pathlib.Path:
    if os.name == "nt":
        return home / "AppData" / "Local" / "AgenticEngineering" / "bin" / "agentic.cmd"
    return home / ".local" / "bin" / "agentic"


def launcher_content() -> str:
    script = REPO / "scripts" / "toolbelt.py"
    if os.name == "nt":
        return f'@py -3 "{script}" %*\r\n'
    return f'#!/bin/sh\nexec python3 {shlex.quote(str(script))} "$@"\n'


def parse_providers(value: str) -> tuple[str, ...]:
    if value == "all":
        return PROVIDERS
    requested = tuple(part.strip() for part in value.split(",") if part.strip())
    unknown = sorted(set(requested) - set(PROVIDERS))
    if unknown:
        raise ToolbeltError(f"unknown provider(s): {', '.join(unknown)}")
    return requested


def install_state_path(home: pathlib.Path) -> pathlib.Path:
    return home.expanduser() / INSTALL_STATE_RELATIVE


def artifact(kind: str, path: pathlib.Path) -> dict[str, str]:
    return {"kind": kind, "path": str(path)}


def desired_artifacts(home: pathlib.Path, group: str) -> list[dict[str, str]]:
    if group == "shared":
        return [artifact("dir", home / ".agents" / "skills" / source.name) for source in skill_dirs()]
    if group == "claude":
        skill_root = REPO / "providers" / "claude" / "skills"
        records = [
            artifact("dir", home / ".claude" / "skills" / source.name)
            for source in sorted(path for path in skill_root.iterdir() if path.is_dir())
        ]
        records.extend(
            artifact("file", home / ".claude" / "agents" / source.name)
            for source in sorted((REPO / "agents").glob("*.md"))
        )
        return records
    if group == "codex":
        return [
            artifact("file", home / ".codex" / "agents" / f"{source.stem}.toml")
            for source in sorted((REPO / "agents").glob("*.md"))
        ]
    if group == "pi":
        records = [
            artifact(
                "dir",
                home / ".pi" / "agent" / "extensions" / "agentic-engineering",
            )
        ]
        records.extend(
            artifact("file", home / ".pi" / "agent" / "agents" / source.name)
            for source in sorted((REPO / "agents").glob("*.md"))
        )
        return records
    if group == "hermes":
        root = hermes_skills_root(home)
        records = [
            artifact("dir", root / source.name) for source in hermes_skill_dirs()
        ]
        records.append(
            artifact("file", root / "agentic-engineering" / "SKILL.md")
        )
        return records
    raise ToolbeltError(f"unknown installation artifact group: {group}")


def detect_installed_providers(home: pathlib.Path) -> set[str]:
    installed: set[str] = set()
    if any(is_managed_dir(path) for path in (home / ".claude" / "skills").glob("*")):
        installed.add("claude")
    if any((home / ".codex" / "agents").glob(".*.agentic-engineering.json")):
        installed.add("codex")
    if is_managed_dir(home / ".pi" / "agent" / "extensions" / "agentic-engineering"):
        installed.add("pi")
    if any(is_managed_dir(path) for path in hermes_skills_root(home).glob("*")):
        installed.add("hermes")
    return installed


def load_install_state(home: pathlib.Path) -> dict[str, object]:
    path = install_state_path(home)
    if not path.is_file():
        return {
            "name": "agentic-engineering",
            "schemaVersion": 1,
            "providers": sorted(detect_installed_providers(home)),
            "artifacts": {},
        }
    try:
        state = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ToolbeltError(f"invalid install state {path}: {exc}") from exc
    if not isinstance(state, dict) or state.get("name") != "agentic-engineering":
        raise ToolbeltError(f"invalid install state owner: {path}")
    if not isinstance(state.get("providers"), list) or not isinstance(state.get("artifacts"), dict):
        raise ToolbeltError(f"invalid install state shape: {path}")
    return state


def write_install_state(home: pathlib.Path, state: dict[str, object]) -> None:
    path = install_state_path(home)
    path.parent.mkdir(parents=True, exist_ok=True)
    if os.name != "nt":
        path.parent.chmod(0o700)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(state, handle, indent=2)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        if os.name != "nt":
            os.chmod(temp_name, 0o600)
        os.replace(temp_name, path)
    finally:
        pathlib.Path(temp_name).unlink(missing_ok=True)


def checked_artifact(record: object, home: pathlib.Path) -> tuple[str, pathlib.Path]:
    if not isinstance(record, dict) or record.get("kind") not in {"dir", "file"}:
        raise ToolbeltError("invalid artifact record in install state")
    raw = record.get("path")
    if not isinstance(raw, str):
        raise ToolbeltError("invalid artifact path in install state")
    path = pathlib.Path(os.path.abspath(os.path.expanduser(raw)))
    home_path = pathlib.Path(os.path.abspath(home.expanduser()))
    # The Hermes skills root may legitimately live outside the home root when
    # $HERMES_HOME points elsewhere (e.g. /data/hermes). Allow the live root AND
    # the root recorded in install state, so re-install/uninstall keep working
    # after $HERMES_HOME changes or is unset.
    allowed = [home_path, pathlib.Path(os.path.abspath(hermes_skills_root(home)))]
    try:
        recorded = load_install_state(home).get("hermesRoot")
    except ToolbeltError:
        recorded = None
    if isinstance(recorded, str):
        allowed.append(pathlib.Path(os.path.abspath(os.path.expanduser(recorded))))
    if not any(
        path == root or path.is_relative_to(root) for root in allowed
    ):
        raise ToolbeltError(f"install state artifact escapes home: {path}")
    return str(record["kind"]), path


def remove_artifact(record: object, home: pathlib.Path, *, dry_run: bool) -> None:
    kind, path = checked_artifact(record, home)
    if kind == "dir":
        remove_managed_dir(path, dry_run=dry_run)
    else:
        remove_managed_file(path, dry_run=dry_run)


def reconcile_artifacts(
    prior: object,
    desired: list[dict[str, str]],
    home: pathlib.Path,
    *,
    dry_run: bool,
) -> None:
    prior_records = prior if isinstance(prior, list) else []
    desired_keys = {(item["kind"], item["path"]) for item in desired}
    for record in prior_records:
        kind, path = checked_artifact(record, home)
        if (kind, str(path)) not in desired_keys:
            remove_artifact(record, home, dry_run=dry_run)


def preflight_managed_dir(destination: pathlib.Path, *, force: bool) -> None:
    """Verify a directory write would succeed, without mutating anything."""
    if (destination.exists() or destination.is_symlink()) and not force:
        require_pristine_managed_dir(destination)


def preflight_managed_file(path: pathlib.Path, *, force: bool) -> None:
    """Verify a file write would succeed, without mutating anything."""
    if path.exists() and not force:
        sidecar = managed_sidecar(path)
        if not sidecar.is_file():
            raise ToolbeltError(f"refusing to replace unmanaged file: {path}")
        try:
            prior = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ToolbeltError(f"invalid managed-file marker: {sidecar}") from exc
        if prior.get("sha256") != sha256(path):
            raise ToolbeltError(f"managed file was edited since installation: {path}")


def install_destinations(
    home: pathlib.Path, providers: tuple[str, ...]
) -> list[tuple[str, pathlib.Path]]:
    """(kind, path) for every destination an install of these providers writes.

    Mirrors the write order and conditions in install() so the whole selected
    artifact set can be preflighted before the first write.
    """
    destinations: list[tuple[str, pathlib.Path]] = [("file", launcher_path(home))]
    if "codex" in providers or "pi" in providers:
        destinations.extend(
            ("dir", home / ".agents" / "skills" / source.name) for source in skill_dirs()
        )
    if "claude" in providers:
        skill_root = REPO / "providers" / "claude" / "skills"
        destinations.extend(
            ("dir", home / ".claude" / "skills" / source.name)
            for source in sorted(path for path in skill_root.iterdir() if path.is_dir())
        )
        destinations.extend(
            ("file", home / ".claude" / "agents" / source.name)
            for source in sorted((REPO / "agents").glob("*.md"))
        )
    if "codex" in providers:
        for _source_path, content in generated_codex_agents().items():
            fields = re.search(r'^name = "([^"]+)"$', content, re.MULTILINE)
            if not fields:
                raise ToolbeltError("generated Codex agent has no name")
            destinations.append(("file", home / ".codex" / "agents" / f"{fields.group(1)}.toml"))
    if "pi" in providers:
        destinations.append(("dir", home / ".pi" / "agent" / "extensions" / "agentic-engineering"))
        destinations.extend(
            ("file", home / ".pi" / "agent" / "agents" / source.name)
            for source in sorted((REPO / "agents").glob("*.md"))
        )
    if "hermes" in providers:
        root = hermes_skills_root(home)
        destinations.extend(("dir", root / source.name) for source in hermes_skill_dirs())
        destinations.append(("file", root / "agentic-engineering" / "SKILL.md"))
    return destinations


def install(home: pathlib.Path, providers: tuple[str, ...], *, force: bool, dry_run: bool) -> None:
    errors = validate_source()
    if errors:
        raise ToolbeltError("source validation failed:\n- " + "\n- ".join(errors))

    state = load_install_state(home)
    installed = set(str(value) for value in state.get("providers", []))
    state_artifacts = state.get("artifacts", {})
    if not isinstance(state_artifacts, dict):
        raise ToolbeltError("invalid install state artifacts")

    # Preflight the entire selected artifact set before the first write, so an
    # unmanaged destination in one provider cannot leave earlier providers
    # half-installed with stale or absent state (mirrors uninstall's preflight).
    # Obsolete records (previously installed, no longer desired) are preflighted
    # too: an edited obsolete artifact must refuse before ANY write, not when
    # reconcile_artifacts reaches it after the launcher and current artifacts.
    desired_paths = {
        str(pathlib.Path(os.path.abspath(destination)))
        for _kind, destination in install_destinations(home, providers)
    }
    for provider in providers:
        prior = state_artifacts.get(provider)
        if isinstance(prior, list):
            for record in prior:
                if str(checked_artifact(record, home)[1]) not in desired_paths:
                    preflight_remove_artifact(record, home)
    if "codex" in providers or "pi" in providers:
        prior_shared = state_artifacts.get("shared")
        if isinstance(prior_shared, list):
            for record in prior_shared:
                if str(checked_artifact(record, home)[1]) not in desired_paths:
                    preflight_remove_artifact(record, home)
    for kind, destination in install_destinations(home, providers):
        if kind == "dir":
            preflight_managed_dir(destination, force=force)
        else:
            preflight_managed_file(destination, force=force)

    write_managed_file(
        launcher_path(home), launcher_content(), force=force, dry_run=dry_run, executable=True
    )

    if "codex" in providers or "pi" in providers:
        destination = home / ".agents" / "skills"
        for source in skill_dirs():
            copy_managed_dir(source, destination / source.name, force=force, dry_run=dry_run)
        shared = desired_artifacts(home, "shared")
        reconcile_artifacts(state_artifacts.get("shared"), shared, home, dry_run=dry_run)
        state_artifacts["shared"] = shared

    if "claude" in providers:
        claude_root = REPO / "providers" / "claude" / "skills"
        for source in sorted(path for path in claude_root.iterdir() if path.is_dir()):
            copy_managed_dir(
                source,
                home / ".claude" / "skills" / source.name,
                force=force,
                dry_run=dry_run,
            )
        for source in sorted((REPO / "agents").glob("*.md")):
            write_managed_file(
                home / ".claude" / "agents" / source.name,
                source.read_text(encoding="utf-8"),
                force=force,
                dry_run=dry_run,
            )
        claude = desired_artifacts(home, "claude")
        reconcile_artifacts(state_artifacts.get("claude"), claude, home, dry_run=dry_run)
        state_artifacts["claude"] = claude

    if "codex" in providers:
        for _source_path, content in generated_codex_agents().items():
            fields = re.search(r'^name = "([^"]+)"$', content, re.MULTILINE)
            if not fields:
                raise ToolbeltError("generated Codex agent has no name")
            write_managed_file(
                home / ".codex" / "agents" / f"{fields.group(1)}.toml",
                content,
                force=force,
                dry_run=dry_run,
            )
        codex = desired_artifacts(home, "codex")
        reconcile_artifacts(state_artifacts.get("codex"), codex, home, dry_run=dry_run)
        state_artifacts["codex"] = codex

    if "pi" in providers:
        copy_managed_dir(
            REPO / "providers" / "pi" / "extensions",
            home / ".pi" / "agent" / "extensions" / "agentic-engineering",
            force=force,
            dry_run=dry_run,
        )
        for source in sorted((REPO / "agents").glob("*.md")):
            write_managed_file(
                home / ".pi" / "agent" / "agents" / source.name,
                source.read_text(encoding="utf-8"),
                force=force,
                dry_run=dry_run,
            )
        pi = desired_artifacts(home, "pi")
        reconcile_artifacts(state_artifacts.get("pi"), pi, home, dry_run=dry_run)
        state_artifacts["pi"] = pi

    if "hermes" in providers:
        hermes_root = hermes_skills_root(home)
        for source in hermes_skill_dirs():
            if source.name == "execute":
                # The executor agent prompt rides inside the execute skill as a
                # linked reference so Hermes can load it with the skill; the
                # extra file is part of the managed snapshot.
                copy_managed_dir(
                    source,
                    hermes_root / source.name,
                    force=force,
                    dry_run=dry_run,
                    extra_files={
                        "references/executor.md": (REPO / "agents" / "executor.md").read_text(
                            encoding="utf-8"
                        )
                    },
                )
                continue
            copy_managed_dir(
                source,
                hermes_root / source.name,
                force=force,
                dry_run=dry_run,
            )
        # The router skill is the Hermes entry point (provider-specific, so it
        # ships from providers/hermes rather than the shared skills/). The
        # __TOOLBELT_REPO__ placeholder is rendered to the real checkout path so
        # the installed router can always resolve the excluded skills.
        router = (REPO / "providers" / "hermes" / "router.md").read_text(encoding="utf-8")
        router = router.replace("__TOOLBELT_REPO__", str(REPO))
        write_managed_file(
            hermes_root / "agentic-engineering" / "SKILL.md",
            router,
            force=force,
            dry_run=dry_run,
        )
        hermes = desired_artifacts(home, "hermes")
        reconcile_artifacts(state_artifacts.get("hermes"), hermes, home, dry_run=dry_run)
        state_artifacts["hermes"] = hermes

    if not dry_run:
        installed.update(providers)
        state["providers"] = sorted(installed)
        state["artifacts"] = state_artifacts
        if "hermes" in installed:
            # Persist the authorized Hermes skills root so reinstall/uninstall
            # still validate recorded artifacts after $HERMES_HOME changes or
            # is unset (the live env may no longer match the install-time root).
            state["hermesRoot"] = str(hermes_skills_root(home))
        write_install_state(home, state)
        print("install complete; start agents from the target application repository")


def remove_managed_dir(path: pathlib.Path, *, dry_run: bool) -> None:
    if not path.exists() and not path.is_symlink():
        return
    require_pristine_managed_dir(path)
    print(f"remove: {path}")
    if not dry_run:
        shutil.rmtree(path)


def remove_managed_file(path: pathlib.Path, *, dry_run: bool) -> None:
    sidecar = managed_sidecar(path)
    if not path.exists() and not sidecar.exists():
        return
    if not path.exists() or not sidecar.is_file():
        raise ToolbeltError(f"refusing partial/unmanaged removal: {path}")
    prior = json.loads(sidecar.read_text(encoding="utf-8"))
    if prior.get("sha256") != sha256(path):
        raise ToolbeltError(f"refusing to remove edited managed file: {path}")
    print(f"remove: {path}")
    if not dry_run:
        path.unlink()
        sidecar.unlink()


def preflight_remove_artifact(record: object, home: pathlib.Path) -> None:
    """Verify a removal would succeed, without mutating anything.

    Mirrors the checks inside remove_artifact/remove_managed_dir/
    remove_managed_file so a refusal surfaces before any deletion starts.
    """
    kind, path = checked_artifact(record, home)
    if kind == "dir":
        if path.exists() or path.is_symlink():
            require_pristine_managed_dir(path)
        return
    sidecar = managed_sidecar(path)
    if not path.exists() and not sidecar.exists():
        return
    if not path.exists() or not sidecar.is_file():
        raise ToolbeltError(f"refusing partial/unmanaged removal: {path}")
    prior = json.loads(sidecar.read_text(encoding="utf-8"))
    if prior.get("sha256") != sha256(path):
        raise ToolbeltError(f"refusing to remove edited managed file: {path}")


def uninstall(home: pathlib.Path, providers: tuple[str, ...], *, dry_run: bool) -> None:
    state = load_install_state(home)
    installed = set(str(value) for value in state.get("providers", []))
    state_artifacts = state.get("artifacts", {})
    if not isinstance(state_artifacts, dict):
        raise ToolbeltError("invalid install state artifacts")
    selected = set(providers)
    remaining = installed - selected
    # Only providers recorded as installed have artifacts to remove. Selecting a
    # provider that was never installed (e.g. hermes, after an upgrade added it
    # to PROVIDERS) must not fabricate desired artifacts and touch the user's
    # own directories.
    to_remove = sorted(selected & installed)

    records_by_provider: dict[str, list[dict[str, str]]] = {}
    for provider in to_remove:
        records = state_artifacts.get(provider)
        if not isinstance(records, list):
            records = desired_artifacts(home, provider)
        records_by_provider[provider] = records
    shared_records: list[dict[str, str]] = []
    if not ({"codex", "pi"} & remaining):
        shared = state_artifacts.get("shared")
        if not isinstance(shared, list):
            shared = desired_artifacts(home, "shared")
        shared_records = shared

    # Preflight the entire removal set before deleting anything, so a refusal on
    # one artifact cannot leave earlier providers half-removed while install
    # state still claims they exist.
    for records in records_by_provider.values():
        for record in records:
            preflight_remove_artifact(record, home)
    for record in shared_records:
        preflight_remove_artifact(record, home)
    if not remaining:
        preflight_remove_artifact(artifact("file", launcher_path(home)), home)

    for provider in to_remove:
        for record in records_by_provider[provider]:
            remove_artifact(record, home, dry_run=dry_run)
        state_artifacts.pop(provider, None)
    for record in shared_records:
        remove_artifact(record, home, dry_run=dry_run)
    if not ({"codex", "pi"} & remaining):
        state_artifacts.pop("shared", None)

    if not remaining:
        remove_managed_file(launcher_path(home), dry_run=dry_run)

    if not dry_run:
        state["providers"] = sorted(remaining)
        state["artifacts"] = state_artifacts
        if "hermes" not in remaining:
            state.pop("hermesRoot", None)
        if remaining:
            write_install_state(home, state)
        else:
            install_state_path(home).unlink(missing_ok=True)


def command_version(name: str) -> tuple[str, str]:
    executable = shutil.which(name)
    if not executable:
        return "missing", ""
    try:
        proc = subprocess.run(
            [executable, "--version"], capture_output=True, text=True, timeout=5, check=False
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return "error", str(exc)
    if proc.returncode != 0:
        return "error", f"exit {proc.returncode}"
    first = (proc.stdout or proc.stderr).strip().splitlines()
    return "available", first[0] if first else executable


def resolve_base(repo: pathlib.Path, *, github_branch: bool) -> str:
    """Resolve one authoritative review base, preferring remote-tracking refs."""
    repo = repo.resolve()

    def git(*args: str) -> subprocess.CompletedProcess[str]:
        try:
            return subprocess.run(
                ["git", "-C", str(repo), *args],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise ToolbeltError(f"git {' '.join(args)} failed: {exc}") from exc

    symbolic = git("symbolic-ref", "--quiet", "--short", "refs/remotes/origin/HEAD")
    candidates: list[str] = []
    if symbolic.returncode == 0 and symbolic.stdout.strip():
        candidates.append(symbolic.stdout.strip())
    candidates.extend(("origin/main", "origin/master", "main", "master"))
    for candidate in dict.fromkeys(candidates):
        if git("rev-parse", "--verify", "--quiet", f"{candidate}^{{commit}}").returncode == 0:
            if github_branch:
                return candidate.removeprefix("refs/remotes/").removeprefix("origin/")
            return candidate
    raise ToolbeltError(
        "could not resolve a base ref from origin/HEAD, origin/main, origin/master, main, or master"
    )


CAPABILITY_HINTS = {
    "claude": "install Claude Code to enable the claude provider (npm install -g @anthropic-ai/claude-code)",
    "codex": "install Codex CLI to enable the codex provider (npm install -g @openai/codex)",
    "pi": "install Pi to enable the pi provider (curl -fsSL https://pi.ai/install | bash)",
    "docker": "install Docker to enable the disposable sandbox (apt install docker.io, brew install --cask docker, or https://docker.com)",
}


def cmux_hint(system_name: str | None = None) -> str:
    """Doctor hint for a missing cmux, tailored to the current platform."""
    if (system_name or platform.system()).lower() == "darwin":
        return "install cmux to enable fleet orchestration (brew install cmux)"
    return "cmux is macOS-only; fleet orchestration is not available on this OS"


def detect_setup_providers() -> tuple[str, ...]:
    """Providers for `agentic setup`: every provider CLI that is available.

    Mirrors the plan's "default is all detected CLIs" — setup installs for the
    agents that actually exist on this machine instead of writing into every
    provider's directory.
    """
    available = tuple(
        name for name in PROVIDERS if command_version(name)[0] == "available"
    )
    return available


def doctor(home: pathlib.Path) -> int:
    print(f"source: {REPO}")
    print(f"platform: {platform.system()} {platform.release()}")
    print(f"python: {platform.python_version()} ({sys.executable})")
    failed = False
    provider_available = False
    for command in ("claude", "codex", "pi", "hermes", "git", "gh", "docker", "cmux", "just"):
        status, detail = command_version(command)
        print(f"{command}: {status}" + (f" ({detail})" if detail else ""))
        if command == "git" and status != "available":
            failed = True
        if command in PROVIDERS and status == "available":
            provider_available = True
    if not provider_available:
        print("provider requirement: missing (install at least one of claude, codex, pi, or hermes)")
        failed = True
    else:
        print("provider requirement: satisfied")
    hermes_files = any(is_managed_dir(path) for path in hermes_skills_root(home).glob("*"))
    print(f"hermes provider files: {'installed' if hermes_files else 'not installed'}")
    launcher = launcher_path(home)
    print(f"launcher: {launcher} ({'installed' if launcher.is_file() else 'missing'})")
    if not launcher.is_file():
        print("hint: run `agentic setup` (or `python3 scripts/toolbelt.py install`) to install the launcher")
    print("capability: core workflow = all platforms")
    print("capability: dashboard watcher = macOS/Linux")
    print("capability: cmux fleet = macOS only")
    print("capability: disposable sandbox = Docker hosts")
    for command in ("claude", "codex", "pi", "docker"):
        status, _ = command_version(command)
        if status != "available":
            print(f"hint: {CAPABILITY_HINTS[command]}")
    cmux_status, _ = command_version("cmux")
    if cmux_status != "available":
        print(f"hint: {cmux_hint()}")
    for variable in ("ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GITHUB_TOKEN"):
        print(f"credential env {variable}: {'present' if os.environ.get(variable) else 'not set'}")
    source_errors = validate_source()
    if source_errors:
        failed = True
        for error in source_errors:
            print(f"source error: {error}")
    else:
        print("source: valid")
    return 1 if failed else 0


def setup(
    home: pathlib.Path,
    providers: tuple[str, ...],
    *,
    force: bool,
    dry_run: bool,
    yes: bool,
) -> int:
    """Guided setup: doctor -> explain -> confirm -> install -> verify -> next steps."""
    print("agentic setup — install the Agentic Engineering toolbelt")
    print("---")
    print("Step 1/4: checking this machine")
    if doctor(home) != 0:
        print("(issues above are informational; setup continues where possible)")
    print("---")
    print(f"Step 2/4: provider integrations to install: {', '.join(providers)}")
    if not yes and sys.stdin.isatty():
        answer = input("Proceed? [Y/n] ").strip().lower()
        if answer in ("n", "no"):
            print("setup cancelled")
            return 1
    print("---")
    print("Step 3/4: installing")
    install(home, providers, force=force, dry_run=dry_run)
    print("---")
    print("Step 4/4: verifying")
    verify_rc = doctor(home)
    if dry_run:
        print("(dry run — nothing was written)")
    print("---")
    print("Next steps:")
    print("  1. agentic init-app <path> --create    bootstrap a new application repo")
    print("  2. cd into that repo and start your agent (claude / codex / pi / hermes)")
    print("  3. /spec <idea> to begin the workflow, or /bugfix for a small fix")
    print("  4. agentic doctor any time to re-check this machine")
    if verify_rc != 0:
        print("setup: verification reported issues above — resolve them before using the toolbelt")
        return verify_rc
    return 0


def read_scaffold_file(path: pathlib.Path) -> bytes | None:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return None
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise ToolbeltError(f"refusing non-regular workflow path: {path}")
    if info.st_size > MAX_SCAFFOLD_BYTES:
        raise ToolbeltError(f"workflow path is too large to compare safely: {path}")
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags)
    except OSError as exc:
        raise ToolbeltError(f"cannot safely read workflow path {path}: {exc}") from exc
    try:
        data = bytearray()
        while len(data) <= MAX_SCAFFOLD_BYTES:
            chunk = os.read(fd, min(64 * 1024, MAX_SCAFFOLD_BYTES + 1 - len(data)))
            if not chunk:
                return bytes(data)
            data.extend(chunk)
    finally:
        os.close(fd)
    raise ToolbeltError(f"workflow path exceeded the safe read limit: {path}")


def ensure_scaffold_parent(target: pathlib.Path, output: pathlib.Path) -> None:
    relative = output.relative_to(target)
    current = target
    for part in relative.parts[:-1]:
        current /= part
        if current.is_symlink():
            raise ToolbeltError(f"refusing symlinked workflow directory: {current}")


def init_app(target: pathlib.Path, *, create: bool) -> None:
    target = pathlib.Path(os.path.abspath(target.expanduser()))
    resolved_target = target.resolve()
    if resolved_target == REPO or REPO in resolved_target.parents:
        raise ToolbeltError("refusing to bootstrap an application inside the toolbelt repository")
    created = False
    if not target.exists():
        if not create:
            raise ToolbeltError(f"target does not exist (pass --create to create it): {target}")
        target.mkdir(parents=True)
        created = True
    if not target.is_dir():
        raise ToolbeltError(f"target is not a directory: {target}")
    if created:
        proc = subprocess.run(["git", "init", "--quiet"], cwd=target, capture_output=True, text=True)
        if proc.returncode:
            raise ToolbeltError(f"could not initialize Git repository: {proc.stderr.strip()}")
        subprocess.run(
            ["git", "symbolic-ref", "HEAD", "refs/heads/main"],
            cwd=target,
            capture_output=True,
            text=True,
            check=False,
        )
    else:
        proc = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            cwd=target,
            capture_output=True,
            text=True,
        )
        if proc.returncode or pathlib.Path(proc.stdout.strip()).resolve() != resolved_target:
            raise ToolbeltError(f"target is not a Git repository root: {target}")

    assets = REPO / "skills" / "new-app" / "assets"
    outputs = {
        target / "AGENTS.md": assets / "AGENTS.md.template",
        target / "CLAUDE.md": assets / "CLAUDE.md.template",
        target / "DEVLOG.md": assets / "DEVLOG.md.template",
        target / "TODO.md": assets / "TODO.md.template",
        target / "specs" / "README.md": assets / "specs-README.md.template",
        target / "plans" / "README.md": assets / "plans-README.md.template",
    }
    conflicts: list[pathlib.Path] = []
    for output, source in outputs.items():
        ensure_scaffold_parent(target, output)
        existing = read_scaffold_file(output)
        if existing is not None and existing != source.read_bytes():
            conflicts.append(output)
    if conflicts:
        raise ToolbeltError(
            "refusing to overwrite existing workflow files:\n- "
            + "\n- ".join(str(path) for path in conflicts)
        )
    for output, source in outputs.items():
        if read_scaffold_file(output) is not None:
            print(f"present: {output}")
            continue
        output.parent.mkdir(parents=True, exist_ok=True)
        ensure_scaffold_parent(target, output)
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
        fd = os.open(output, flags, 0o644)
        with os.fdopen(fd, "wb") as handle:
            handle.write(source.read_bytes())
        print(f"created: {output}")
    print("next gate: commit the bootstrap, then run wayfinder if the product is foggy; otherwise run spec")


def run_repo_script(path: pathlib.Path, args: Iterable[str]) -> int:
    proc = subprocess.run([sys.executable, str(path), *args], cwd=REPO, check=False)
    return proc.returncode


def run_sandbox(repo: pathlib.Path, *, online: bool, command: list[str]) -> int:
    archive = REPO / ".sandbox" / "source.tar"
    archive.parent.mkdir(parents=True, exist_ok=True)
    prepared = run_repo_script(
        REPO / "scripts" / "sandbox" / "prepare_archive.py",
        ["--repo", str(repo), "--output", str(archive)],
    )
    if prepared:
        return prepared
    service = "sandbox-online" if online else "sandbox"
    args = [
        "docker", "compose", "-f", str(REPO / "sandbox" / "compose.yaml"),
        "run", "--rm", service,
    ]
    if command and command[0] == "--":
        command = command[1:]
    args.extend(command)
    return subprocess.run(
        args,
        cwd=REPO,
        env={**os.environ, "AGENTIC_SANDBOX_ARCHIVE": str(archive)},
        check=False,
    ).returncode


def selftest() -> int:
    ambient_hermes_home = os.environ.get("HERMES_HOME")
    try:
        with tempfile.TemporaryDirectory(prefix="agentic-toolbelt-selftest-") as raw:
            root = pathlib.Path(raw)
            home = root / "home"
            home.mkdir()
            # Isolate the selftest from any ambient $HERMES_HOME: hermes installs
            # during the gate must never write to (or clean up) a real Hermes
            # home — override it to a directory under the temp root for the
            # whole selftest and restore it in finally.
            os.environ["HERMES_HOME"] = str(root / "hermes-home-selftest")
            output = io.StringIO()
        if generate(check=True):
            raise AssertionError("generated provider adapters are stale")
        if validate_source():
            raise AssertionError("source validation failed")
        # Descriptions must survive adapter generation without escaping drift:
        # the parsed canonical description must equal the parsed Claude-mirror
        # description, and the mirror must carry real Unicode (no \uXXXX) — this
        # pins the fix for the double-escaping / — regression.
        for directory in skill_dirs():
            canonical_fields, _ = parse_frontmatter(directory / "SKILL.md")
            mirror = REPO / "providers" / "claude" / "skills" / directory.name / "SKILL.md"
            mirror_fields, _ = parse_frontmatter(mirror)
            if canonical_fields.get("description") != mirror_fields.get("description"):
                raise AssertionError(f"description not faithfully generated for {directory.name}")
            for mirror_line in mirror.read_text(encoding="utf-8").splitlines():
                if mirror_line.startswith("description:"):
                    if "\\u" in mirror_line:
                        raise AssertionError(f"generated adapter for {directory.name} escapes unicode in its description")
                    break
        with contextlib.redirect_stdout(output):
            install(home, PROVIDERS, force=False, dry_run=False)
        assert (home / ".agents" / "skills" / "spec" / "SKILL.md").is_file()
        assert (home / ".claude" / "skills" / "spec" / "SKILL.md").is_file()
        assert "disable-model-invocation: true" in (
            home / ".claude" / "skills" / "spec" / "SKILL.md"
        ).read_text(encoding="utf-8")
        assert (home / ".claude" / "agents" / "executor.md").is_file()
        assert (home / ".codex" / "agents" / "executor.toml").is_file()
        assert (home / ".pi" / "agent" / "extensions" / "agentic-engineering" / "subagent.ts").is_file()
        hermes_root = hermes_skills_root(home)
        assert (hermes_root / "spec" / "SKILL.md").is_file()
        assert (hermes_root / "execute" / "references" / "executor.md").is_file()
        assert (hermes_root / "agentic-engineering" / "SKILL.md").is_file()
        for excluded in HERMES_EXCLUDED:
            assert not (hermes_root / excluded).exists(), (
                f"hermes install must exclude bundled-name skill {excluded}"
            )
        with contextlib.redirect_stdout(output):
            install(home, PROVIDERS, force=False, dry_run=False)

        managed_spec = home / ".agents" / "skills" / "spec"
        managed_before = managed_dir_snapshot(managed_spec)
        original_copytree = shutil.copytree
        try:
            def fail_copytree(source, destination, **kwargs):
                pathlib.Path(destination).mkdir(parents=True)
                (pathlib.Path(destination) / "partial").write_text("partial\n", encoding="utf-8")
                raise OSError("simulated copy failure")

            shutil.copytree = fail_copytree
            try:
                copy_managed_dir(REPO / "skills" / "spec", managed_spec, force=False, dry_run=False)
            except OSError:
                pass
            else:
                raise AssertionError("managed directory copy failure did not surface")
        finally:
            shutil.copytree = original_copytree
        assert managed_dir_snapshot(managed_spec) == managed_before

        with contextlib.redirect_stdout(output):
            uninstall(home, ("codex",), dry_run=False)
        assert (home / ".agents" / "skills" / "spec" / "SKILL.md").is_file()
        assert (home / ".pi" / "agent" / "extensions" / "agentic-engineering").is_dir()
        assert launcher_path(home).is_file()
        assert not (home / ".codex" / "agents" / "executor.toml").exists()
        with contextlib.redirect_stdout(output):
            install(home, ("codex",), force=False, dry_run=False)

        skill_file = home / ".agents" / "skills" / "spec" / "SKILL.md"
        skill_file.write_text(skill_file.read_text(encoding="utf-8") + "\nlocal edit\n", encoding="utf-8")
        try:
            with contextlib.redirect_stdout(output):
                install(home, ("pi",), force=False, dry_run=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("install overwrote an edited managed directory")
        with contextlib.redirect_stdout(output):
            install(home, ("pi",), force=True, dry_run=False)

        obsolete = home / ".agents" / "skills" / "obsolete"
        copy_managed_dir(REPO / "skills" / "spec", obsolete, force=False, dry_run=False)
        state = load_install_state(home)
        artifacts = state["artifacts"]
        assert isinstance(artifacts, dict)
        shared = artifacts["shared"]
        assert isinstance(shared, list)
        shared.append(artifact("dir", obsolete))
        write_install_state(home, state)
        with contextlib.redirect_stdout(output):
            install(home, ("pi",), force=False, dry_run=False)
        assert not obsolete.exists()

        app = root / "app"
        with contextlib.redirect_stdout(output):
            init_app(app, create=True)
        assert (app / ".git").is_dir()
        before = {path.relative_to(app): path.read_bytes() for path in app.rglob("*") if path.is_file()}
        with contextlib.redirect_stdout(output):
            init_app(app, create=False)
        after = {path.relative_to(app): path.read_bytes() for path in app.rglob("*") if path.is_file()}
        assert before == after
        (app / "AGENTS.md").write_text("local policy\n", encoding="utf-8")
        try:
            with contextlib.redirect_stdout(output):
                init_app(app, create=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("init-app overwrote an existing file")

        malicious = root / "malicious"
        malicious.mkdir()
        subprocess.run(["git", "init", "--quiet"], cwd=malicious, check=True)
        (malicious / "AGENTS.md").symlink_to("/dev/zero")
        try:
            with contextlib.redirect_stdout(output):
                init_app(malicious, create=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("init-app followed a scaffold symlink")

        original_command_version = globals()["command_version"]
        try:
            globals()["command_version"] = lambda name: (
                ("available", "test") if name in {"git", "codex"} else ("missing", "")
            )
            with contextlib.redirect_stdout(output):
                if doctor(home) != 0:
                    raise AssertionError("doctor rejected Git plus one available provider")
        finally:
            globals()["command_version"] = original_command_version

        with contextlib.redirect_stdout(output):
            uninstall(home, PROVIDERS, dry_run=False)
        assert not (home / ".codex" / "agents" / "executor.toml").exists()
        assert not launcher_path(home).exists()
        assert not install_state_path(home).exists()

        # setup wizard: non-interactive install, next-steps banner. Mock the
        # provider CLIs so doctor's verification passes on any runner (no real
        # hermes/claude/codex/pi required), and so the propagated rc is 0.
        original_cv_setup = globals()["command_version"]
        try:
            def ci_safe_cv(name: str):
                if name in ("git", "codex"):
                    return ("available", "test")
                return ("missing", "")

            globals()["command_version"] = ci_safe_cv
            with contextlib.redirect_stdout(output):
                setup_rc = setup(home, ("hermes",), force=False, dry_run=False, yes=True)
        finally:
            globals()["command_version"] = original_cv_setup
        assert setup_rc == 0
        assert "Next steps" in output.getvalue()
        assert launcher_path(home).is_file()
        assert (hermes_skills_root(home) / "spec" / "SKILL.md").is_file()

        # doctor hints: a missing capability gets a remedy line; an installed
        # launcher does not get the launcher hint.
        original_command_version = globals()["command_version"]
        try:
            def missing_docker(name: str):
                if name == "docker":
                    return ("missing", "")
                return original_command_version(name)

            globals()["command_version"] = missing_docker
            hints_output = io.StringIO()
            with contextlib.redirect_stdout(hints_output):
                doctor(home)
            assert "hint: install Docker" in hints_output.getvalue()
            assert "hint: run `agentic setup`" not in hints_output.getvalue()
        finally:
            globals()["command_version"] = original_command_version

        # --- Codex-review regression tests ---

        # Router rendering: the installed router carries the real REPO path, not
        # the placeholder (P2: resolvable toolbelt path).
        router_text = (
            hermes_skills_root(home) / "agentic-engineering" / "SKILL.md"
        ).read_text(encoding="utf-8")
        assert "__TOOLBELT_REPO__" not in router_text
        assert str(REPO) in router_text

        # HERMES_HOME outside the home root: install, re-install, and uninstall
        # all succeed — checked_artifact must allow the external skills root
        # (P2: state validation vs the documented $HERMES_HOME override).
        external_hermes = root / "hermes-home"
        original_hermes_home = os.environ.get("HERMES_HOME")
        try:
            os.environ["HERMES_HOME"] = str(external_hermes)
            with contextlib.redirect_stdout(output):
                install(home, ("hermes",), force=False, dry_run=False)
            assert (external_hermes / "skills" / "spec" / "SKILL.md").is_file()
        finally:
            if original_hermes_home is None:
                os.environ.pop("HERMES_HOME", None)
            else:
                os.environ["HERMES_HOME"] = original_hermes_home
        # With $HERMES_HOME unset, reinstall + uninstall must still work via the
        # root persisted in install state (P2: no environment-dependence).
        with contextlib.redirect_stdout(output):
            install(home, ("hermes",), force=False, dry_run=False)
            uninstall(home, ("hermes",), dry_run=False)
        assert not (external_hermes / "skills" / "spec").exists()

        # detect_setup_providers: only available CLIs are selected (P2: setup
        # must not default to every provider).
        original_cv = globals()["command_version"]
        try:
            def fake_cv(name: str):
                if name == "codex":
                    return ("available", "codex-cli test")
                return ("missing", "")

            globals()["command_version"] = fake_cv
            assert detect_setup_providers() == ("codex",)
        finally:
            globals()["command_version"] = original_cv

        # doctor probes the hermes CLI: a hermes-only machine reports the
        # provider requirement satisfied (P2: executable, not artifact files).
        try:
            def hermes_only(name: str):
                if name == "hermes":
                    return ("available", "hermes test")
                if name == "git":
                    return ("available", "git test")
                return ("missing", "")

            globals()["command_version"] = hermes_only
            probe_output = io.StringIO()
            with contextlib.redirect_stdout(probe_output):
                doctor(home)
            assert "provider requirement: satisfied" in probe_output.getvalue()
            assert "hermes: available" in probe_output.getvalue()
        finally:
            globals()["command_version"] = original_cv

        # cmux hint is platform-aware (P3).
        assert "install cmux" in cmux_hint("darwin")
        assert "macOS-only" in cmux_hint("linux")

        # uninstall skips providers never installed (P1): a full uninstall after
        # a codex-only install must not select hermes or touch the user's own
        # unmanaged Hermes skill directories.
        with contextlib.redirect_stdout(output):
            uninstall(home, PROVIDERS, dry_run=False)
        with contextlib.redirect_stdout(output):
            install(home, ("codex",), force=False, dry_run=False)
        user_skill = home / ".hermes" / "skills" / "user-skill"
        user_skill.mkdir(parents=True)
        (user_skill / "SKILL.md").write_text("user's own skill\n", encoding="utf-8")
        with contextlib.redirect_stdout(output):
            uninstall(home, PROVIDERS, dry_run=False)
        assert user_skill.is_dir()
        assert not (home / ".codex" / "agents" / "executor.toml").exists()
        assert not install_state_path(home).exists()

        # Preflight atomicity (P1): a refusal on one artifact aborts the whole
        # uninstall before anything is deleted, and install state stays intact.
        with contextlib.redirect_stdout(output):
            install(home, ("codex", "pi"), force=False, dry_run=False)
        executor_toml = home / ".codex" / "agents" / "executor.toml"
        executor_toml.write_text(
            executor_toml.read_text(encoding="utf-8") + "\nedited\n", encoding="utf-8"
        )
        try:
            with contextlib.redirect_stdout(output):
                uninstall(home, ("codex", "pi"), dry_run=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("uninstall with an edited managed file must refuse")
        assert executor_toml.exists()
        assert (home / ".pi" / "agent" / "extensions" / "agentic-engineering").is_dir()
        assert load_install_state(home)["providers"] == sorted({"codex", "pi"})
        with contextlib.redirect_stdout(output):
            install(home, ("codex", "pi"), force=True, dry_run=False)  # restore pristine
        with contextlib.redirect_stdout(output):
            uninstall(home, PROVIDERS, dry_run=False)

        # --- Codex review round 2 regression tests ---

        # command_version classifies a nonzero --version exit as error, so a
        # broken executable cannot satisfy the provider requirement (P2).
        # Exercise it through `git` — a hard gate requirement present on every
        # runner — so the test never depends on `hermes` being installed.
        original_subprocess_run = subprocess.run
        try:
            class FailingProc:
                returncode = 2
                stdout = ""
                stderr = "boom"

            subprocess.run = lambda *a, **k: FailingProc()  # type: ignore[assignment]
            status, detail = command_version("git")
            assert status == "error" and "exit 2" in detail
        finally:
            subprocess.run = original_subprocess_run

        # doctor --hints is a valid documented interface (P2).
        parsed = parser().parse_args(["doctor", "--hints"])
        assert parsed.command == "doctor" and parsed.hints is True

        # Install preflight (P1): an unmanaged dir at a REAL destination aborts
        # the install before ANY write — the launcher must not appear and state
        # must not exist.
        blocked = home / ".claude" / "skills" / "spec"
        blocked.mkdir(parents=True)
        (blocked / "SKILL.md").write_text("unmanaged\n", encoding="utf-8")
        try:
            with contextlib.redirect_stdout(output):
                install(home, ("claude",), force=False, dry_run=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("install with an unmanaged destination must refuse")
        assert not launcher_path(home).exists(), "preflight must abort before the launcher write"
        assert not install_state_path(home).exists()
        shutil.rmtree(blocked)

        # A corrupt managed-file sidecar surfaces as ToolbeltError during
        # preflight, not an uncaught JSONDecodeError (P2).
        fake_file = home / "probe.txt"
        fake_file.write_text("x\n", encoding="utf-8")
        (home / ".probe.txt.agentic-engineering.json").write_text("{", encoding="utf-8")
        try:
            preflight_managed_file(fake_file, force=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("corrupt sidecar must raise ToolbeltError, not JSONDecodeError")
        fake_file.unlink()
        (home / ".probe.txt.agentic-engineering.json").unlink()

        # A relative $HERMES_HOME is normalized to an absolute root (P2):
        # relative records would corrupt artifact reconciliation.
        os.environ["HERMES_HOME"] = "rel-hermes"
        try:
            normalized = hermes_skills_root(home)
            assert os.path.isabs(normalized) and normalized.parent.name == "rel-hermes"
        finally:
            os.environ["HERMES_HOME"] = str(root / "hermes-home-selftest")

        # Obsolete-artifact preflight (P2): an edited artifact that is no longer
        # desired refuses the install before any write — reconcile must never
        # hit it after the launcher and current artifacts were written.
        with contextlib.redirect_stdout(output):
            install(home, ("codex",), force=False, dry_run=False)
        obsolete = home / ".codex" / "agents" / "obsolete.toml"
        write_managed_file(obsolete, "managed\n", force=False, dry_run=False)
        state = load_install_state(home)
        artifacts = state.get("artifacts")
        if isinstance(artifacts, dict):
            codex_records = artifacts.get("codex")
            if isinstance(codex_records, list):
                codex_records.append(artifact("file", obsolete))
                write_install_state(home, state)
        obsolete.write_text("managed\nEDITED\n", encoding="utf-8")  # break the hash
        try:
            with contextlib.redirect_stdout(output):
                install(home, ("codex",), force=False, dry_run=False)
        except ToolbeltError:
            pass
        else:
            raise AssertionError("edited obsolete artifact must refuse install before writes")
        assert obsolete.exists()
        # clean up the fabricated obsolete artifact so the final state is tidy
        obsolete.unlink()
        managed_sidecar(obsolete).unlink()
        state = load_install_state(home)
        artifacts = state.get("artifacts")
        if isinstance(artifacts, dict):
            codex_records = artifacts.get("codex")
            if isinstance(codex_records, list):
                artifacts["codex"] = [
                    r for r in codex_records if str(r.get("path")) != str(obsolete)
                ]
                write_install_state(home, state)
        with contextlib.redirect_stdout(output):
            uninstall(home, ("codex",), dry_run=False)
    finally:
        if ambient_hermes_home is None:
            os.environ.pop("HERMES_HOME", None)
        else:
            os.environ["HERMES_HOME"] = ambient_hermes_home
    print("toolbelt selftest: OK")
    return 0


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(prog="agentic", description=__doc__)
    sub = root.add_subparsers(dest="command", required=True)

    install_parser = sub.add_parser("install", help="Install or update provider integrations")
    install_parser.add_argument("--home", type=pathlib.Path, default=pathlib.Path.home())
    install_parser.add_argument("--providers", default="all")
    install_parser.add_argument("--force", action="store_true")
    install_parser.add_argument("--dry-run", action="store_true")

    uninstall_parser = sub.add_parser("uninstall", help="Remove only managed provider integrations")
    uninstall_parser.add_argument("--home", type=pathlib.Path, default=pathlib.Path.home())
    uninstall_parser.add_argument("--providers", default="all")
    uninstall_parser.add_argument("--dry-run", action="store_true")

    doctor_parser = sub.add_parser("doctor", help="Report prerequisites and provider capabilities")
    doctor_parser.add_argument("--home", type=pathlib.Path, default=pathlib.Path.home())
    doctor_parser.add_argument(
        "--hints",
        action="store_true",
        help="accepted for compatibility; hint lines print by default",
    )

    setup_parser = sub.add_parser("setup", help="Guided install: doctor, explain, install, verify")
    setup_parser.add_argument("--home", type=pathlib.Path, default=pathlib.Path.home())
    setup_parser.add_argument(
        "--providers",
        default=None,
        help="comma-separated subset; default is every provider CLI detected on this machine",
    )
    setup_parser.add_argument("--yes", action="store_true", help="skip the confirmation prompt")
    setup_parser.add_argument("--force", action="store_true")
    setup_parser.add_argument("--dry-run", action="store_true")

    init_parser = sub.add_parser("init-app", help="Bootstrap an application repository")
    init_parser.add_argument("target", type=pathlib.Path)
    init_parser.add_argument("--create", action="store_true")

    generate_parser = sub.add_parser("generate", help="Generate provider-specific adapters")
    generate_parser.add_argument("--check", action="store_true")

    sub.add_parser("check", help="Validate the provider-neutral source and generated adapters")
    sub.add_parser("gate", help="Run the repository's complete local gate")

    dashboard_parser = sub.add_parser("dashboard", help="Run the worktree dashboard")
    dashboard_parser.add_argument("args", nargs=argparse.REMAINDER)

    fleet_parser = sub.add_parser("cmux-fleet", help="Bootstrap a cmux fleet")
    fleet_parser.add_argument("args", nargs=argparse.REMAINDER)

    send_parser = sub.add_parser("cmux-send", help="Send a safe task to a cmux surface")
    send_parser.add_argument("args", nargs=argparse.REMAINDER)

    eval_parser = sub.add_parser("eval", help="Run a skill's eval scenarios through an agent CLI")
    eval_parser.add_argument("args", nargs=argparse.REMAINDER)

    manifest_parser = sub.add_parser("cmux-manifest", help="Validate and locate a fleet manifest")
    manifest_parser.add_argument("slug")
    manifest_parser.add_argument("--repo", type=pathlib.Path, default=pathlib.Path.cwd())

    sandbox_parser = sub.add_parser("sandbox", help="Run a committed repository in the disposable sandbox")
    sandbox_parser.add_argument("--repo", type=pathlib.Path, default=pathlib.Path.cwd())
    sandbox_parser.add_argument("--online", action="store_true")
    sandbox_parser.add_argument("sandbox_command", nargs=argparse.REMAINDER)

    base_parser = sub.add_parser("resolve-base", help="Resolve the authoritative Git review base")
    base_parser.add_argument("--repo", type=pathlib.Path, default=pathlib.Path.cwd())
    base_parser.add_argument("--github-branch", action="store_true")

    sub.add_parser("check-upstream", help="Check pinned upstream skill sources for drift")

    return root


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    if argv == ["--selftest"]:
        return selftest()
    # These commands are dispatched before argparse so REMAINDER-style flags
    # (including --help) reach the target script untouched; their argparse
    # subparsers exist only so `agentic --help` lists them.
    forwarded = {
        "dashboard": REPO / "scripts" / "dashboard" / "dashboard.py",
        "cmux-fleet": REPO / "scripts" / "cmux" / "spawn_fleet.py",
        "cmux-send": REPO / "scripts" / "cmux" / "send_task.py",
        "eval": REPO / "scripts" / "eval" / "run_eval.py",
        "check-upstream": REPO / "scripts" / "maintenance" / "check_upstream.py",
    }
    if argv and argv[0] in forwarded:
        return run_repo_script(forwarded[argv[0]], argv[1:])
    args = parser().parse_args(argv)
    try:
        if args.command == "setup":
            if args.providers is None:
                providers = detect_setup_providers()
                if not providers:
                    print(
                        "agentic setup: no provider CLI detected (claude, codex, pi, hermes). "
                        "Install one, or pass --providers explicitly."
                    )
                    return 1
            else:
                providers = parse_providers(args.providers)
            return setup(
                args.home,
                providers,
                force=args.force,
                dry_run=args.dry_run,
                yes=args.yes,
            )
        if args.command == "install":
            install(args.home, parse_providers(args.providers), force=args.force, dry_run=args.dry_run)
            return 0
        if args.command == "uninstall":
            uninstall(args.home, parse_providers(args.providers), dry_run=args.dry_run)
            return 0
        if args.command == "doctor":
            return doctor(args.home)
        if args.command == "init-app":
            init_app(args.target, create=args.create)
            return 0
        if args.command == "generate":
            return generate(check=args.check)
        if args.command == "check":
            errors = validate_source()
            if errors:
                for error in errors:
                    print(error)
                return 1
            print("toolbelt source: valid")
            return 0
        if args.command == "gate":
            return run_repo_script(REPO / "scripts" / "ci" / "check_all.py", [])
        if args.command == "cmux-manifest":
            return run_repo_script(
                REPO / "scripts" / "cmux" / "spawn_fleet.py",
                ["--repo", str(args.repo), "--print-manifest", args.slug],
            )
        if args.command == "sandbox":
            return run_sandbox(args.repo, online=args.online, command=args.sandbox_command)
        if args.command == "resolve-base":
            print(resolve_base(args.repo, github_branch=args.github_branch))
            return 0
        raise ToolbeltError(f"unsupported command: {args.command}")
    except ToolbeltError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
